# Generated by Django 5.2.7 on 2025-12-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_bio_user_club_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='offers_mentoring',
            field=models.BooleanField(default=False),
        ),
    ]
