# Generated by Django 5.2.7 on 2025-12-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_languages_user_offers_mentoring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='competencies',
            new_name='skills',
        ),
    ]
