# Generated by Django 6.0.1 on 2026-02-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_email_verification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='users_email_user_id_0b55cf_idx',
            old_name='users_email_user_id_4b7ebf_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='users_email_expires_7cc044_idx',
            old_name='users_email_expires_5ef9c9_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_user_id_225c30_idx',
            old_name='users_pass_user_id_8a4e5e_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_expires_853bc2_idx',
            old_name='users_pass_expires_a3d1f7_idx',
        ),
    ]
