# Generated by Django 5.2.7 on 2025-12-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_skill_softskill_remove_user_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='softskill',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
