# Generated by Django 5.2.7 on 2025-12-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_skill_translations_softskill_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='club_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='club_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='club_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='club_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='club_members_count',
            field=models.IntegerField(default=0, help_text='Number of members in the club'),
        ),
        migrations.AddField(
            model_name='user',
            name='club_sister_clubs_count',
            field=models.IntegerField(default=0, help_text='Number of sister clubs'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('NORMAL', 'Normal User'), ('CLUB', 'Club')], default='NORMAL', max_length=10),
        ),
    ]
