# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_club_president'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rotary_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
