# Generated by ChatGPT on 2026-01-15
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_rotary_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='focus_areas',
            field=models.ManyToManyField(blank=True, to='users.focusarea'),
        ),
    ]
