# Generated by Django 5.2.7 on 2026-09-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text='Codice ISO 639-1: it, en, es, fr...', max_length=10, unique=True, verbose_name='codice')),
                ('nome', models.CharField(help_text='Il nome nella lingua stessa: Italiano, English, Espanol.', max_length=60, verbose_name='nome')),
                ('attiva', models.BooleanField(default=True, help_text='Se spenta, il sito smette di servirla e di tradurre verso di essa. Le traduzioni gia fatte restano.', verbose_name='attiva')),
                ('ordine', models.IntegerField(default=0, verbose_name='ordine')),
            ],
            options={
                'verbose_name': 'lingua',
                'verbose_name_plural': 'lingue',
                'ordering': ['ordine', 'codice'],
            },
        ),
    ]
