# Generated by Django 5.2.7 on 2026-09-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text='Codice ISO 639-1: it, en, es, fr...', max_length=10, unique=True, verbose_name='codice')),
                ('nome', models.CharField(help_text='Il nome nella lingua stessa: Italiano, English, Espanol.', max_length=60, verbose_name='nome')),
                ('attiva', models.BooleanField(default=True, help_text='Se spenta, il sito smette di servirla e di tradurre verso di essa. Le traduzioni gia fatte restano.', verbose_name='attiva')),
                ('ordine', models.IntegerField(default=0, verbose_name='ordine')),
            ],
            options={
                'verbose_name': 'lingua',
                'verbose_name_plural': 'lingue',
                'ordering': ['ordine', 'codice'],
            },
        ),
        migrations.CreateModel(
            name='Traduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('target_language', models.CharField(max_length=10, verbose_name='lingua')),
                ('source_language', models.CharField(max_length=10, verbose_name='lingua di stesura')),
                ('texts', models.JSONField(blank=True, default=dict, verbose_name='testi')),
                ('locked_paths', models.JSONField(blank=True, default=list, verbose_name='percorsi bloccati')),
                ('human_locked', models.BooleanField(default=False, verbose_name='corretta a mano')),
                ('needs_review', models.BooleanField(db_index=True, default=False, verbose_name='da rivedere')),
                ('provider', models.CharField(blank=True, choices=[('claude', 'Modello linguistico'), ('identita', 'Nessuna traduzione (testo originale)'), ('umano', 'Scritta da una persona')], max_length=20)),
                ('source_digest', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'traduzione',
                'verbose_name_plural': 'traduzioni',
                'ordering': ['-needs_review', '-updated_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'target_language'], name='traduzione__content_e2cbf3_idx'), models.Index(fields=['target_language', 'needs_review'], name='traduzione__target__9b4966_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'target_language'), name='uniq_traduzione_oggetto_lingua')],
            },
        ),
    ]
