from django.core.management.base import BaseCommand

from users.models import Skill, SoftSkill


BASE_HARD_SKILLS = [
    ("Project Management", "Gestione Progetti"),
    ("Program Management", "Gestione Programmi"),
    ("Product Management", "Gestione Prodotto"),
    ("Business Analysis", "Analisi di Business"),
    ("Strategic Planning", "Pianificazione Strategica"),
    ("Business Development", "Sviluppo Business"),
    ("Entrepreneurship", "Imprenditorialita"),
    ("Fundraising", "Raccolta Fondi"),
    ("Grant Writing", "Scrittura Bandi"),
    ("Financial Planning", "Pianificazione Finanziaria"),
    ("Accounting", "Contabilita"),
    ("Budgeting", "Gestione Budget"),
    ("Risk Management", "Gestione Rischi"),
    ("Compliance", "Conformita Normativa"),
    ("Legal Consulting", "Consulenza Legale"),
    ("Contract Management", "Gestione Contratti"),
    ("Public Policy", "Politiche Pubbliche"),
    ("Public Administration", "Amministrazione Pubblica"),
    ("Procurement", "Approvvigionamento"),
    ("Supply Chain Management", "Gestione Supply Chain"),
    ("Operations Management", "Gestione Operativa"),
    ("Quality Assurance", "Assicurazione Qualita"),
    ("Lean Management", "Lean Management"),
    ("Six Sigma", "Six Sigma"),
    ("Software Development", "Sviluppo Software"),
    ("Web Development", "Sviluppo Web"),
    ("Mobile Development", "Sviluppo Mobile"),
    ("Cloud Computing", "Cloud Computing"),
    ("DevOps", "DevOps"),
    ("Cybersecurity", "Sicurezza Informatica"),
    ("Network Administration", "Amministrazione di Rete"),
    ("Database Administration", "Amministrazione Database"),
    ("Data Analysis", "Analisi Dati"),
    ("Data Science", "Data Science"),
    ("Machine Learning", "Machine Learning"),
    ("AI Prompt Engineering", "Prompt Engineering AI"),
    ("Business Intelligence", "Business Intelligence"),
    ("Digital Transformation", "Trasformazione Digitale"),
    ("UX/UI Design", "Design UX/UI"),
    ("Graphic Design", "Design Grafico"),
    ("Content Strategy", "Strategia Contenuti"),
    ("Copywriting", "Copywriting"),
    ("Digital Marketing", "Marketing Digitale"),
    ("Social Media Management", "Gestione Social Media"),
    ("SEO/SEM", "SEO/SEM"),
    ("Brand Management", "Gestione Brand"),
    ("Public Relations", "Pubbliche Relazioni"),
    ("Sales Management", "Gestione Vendite"),
    ("Customer Success", "Customer Success"),
    ("Event Planning", "Pianificazione Eventi"),
    ("Hospitality Management", "Gestione Ospitalita"),
    ("Teaching", "Insegnamento"),
    ("Instructional Design", "Progettazione Didattica"),
    ("Curriculum Development", "Sviluppo Curriculum"),
    ("Training Delivery", "Erogazione Formazione"),
    ("Career Coaching", "Career Coaching"),
    ("Medical Research", "Ricerca Medica"),
    ("Public Health", "Sanita Pubblica"),
    ("Nursing", "Assistenza Infermieristica"),
    ("Clinical Management", "Gestione Clinica"),
    ("Psychology", "Psicologia"),
    ("Architecture", "Architettura"),
    ("Civil Engineering", "Ingegneria Civile"),
    ("Mechanical Engineering", "Ingegneria Meccanica"),
    ("Electrical Engineering", "Ingegneria Elettrica"),
    ("Environmental Engineering", "Ingegneria Ambientale"),
    ("Energy Management", "Gestione Energetica"),
    ("Sustainability Management", "Gestione Sostenibilita"),
    ("ESG Reporting", "Reportistica ESG"),
    ("Agronomy", "Agronomia"),
    ("Food Safety", "Sicurezza Alimentare"),
    ("International Relations", "Relazioni Internazionali"),
    ("Translation & Localization", "Traduzione e Localizzazione"),
]

REQUESTED_HARD_SKILLS = [
    ("Software Engineer", "Ingegnere Software"),
    ("Backend Developer", "Sviluppatore Backend"),
    ("Frontend Developer", "Sviluppatore Frontend"),
    ("Full Stack Developer", "Sviluppatore Full Stack"),
    ("Mobile Developer", "Sviluppatore Mobile"),
    ("Game Developer", "Sviluppatore di Videogiochi"),
    ("Embedded Systems Engineer", "Ingegnere Sistemi Embedded"),
    ("Firmware Engineer", "Ingegnere Firmware"),
    ("DevOps Engineer", "Ingegnere DevOps"),
    ("Site Reliability Engineer", "Ingegnere di Affidabilita dei Sistemi"),
    ("QA Engineer", "Ingegnere QA"),
    ("Test Automation Engineer", "Ingegnere di Automazione Test"),
    ("Security Engineer", "Ingegnere della Sicurezza"),
    ("Cloud Engineer", "Ingegnere Cloud"),
    ("Platform Engineer", "Ingegnere di Piattaforma"),
    ("Data Scientist", "Data Scientist"),
    ("Data Analyst", "Analista Dati"),
    ("Data Engineer", "Ingegnere Dati"),
    ("Machine Learning Engineer", "Ingegnere Machine Learning"),
    ("AI Engineer", "Ingegnere AI"),
    ("NLP Engineer", "Ingegnere NLP"),
    ("Computer Vision Engineer", "Ingegnere Computer Vision"),
    ("MLOps Engineer", "Ingegnere MLOps"),
    ("BI Developer", "Sviluppatore BI"),
    ("Quantitative Analyst", "Analista Quantitativo"),
    ("Network Engineer", "Ingegnere di Rete"),
    ("System Administrator", "Amministratore di Sistema"),
    ("IT Support Specialist", "Specialista Supporto IT"),
    ("SOC Analyst", "Analista SOC"),
    ("Penetration Tester", "Penetration Tester"),
    ("Cybersecurity Analyst", "Analista Cybersecurity"),
    ("Security Architect", "Architetto della Sicurezza"),
    ("Cloud Architect", "Architetto Cloud"),
    ("Product Manager", "Product Manager"),
    ("Product Owner", "Product Owner"),
    ("Technical Product Manager", "Technical Product Manager"),
    ("UX Designer", "UX Designer"),
    ("UI Designer", "UI Designer"),
    ("UX Researcher", "Ricercatore UX"),
    ("Interaction Designer", "Interaction Designer"),
    ("Service Designer", "Service Designer"),
    ("Graphic Designer", "Graphic Designer"),
    ("Motion Designer", "Motion Designer"),
    ("Project Manager", "Project Manager"),
    ("Program Manager", "Program Manager"),
    ("Operations Manager", "Operations Manager"),
    ("Business Analyst", "Business Analyst"),
    ("Strategy Consultant", "Consulente Strategico"),
    ("Management Consultant", "Consulente di Direzione"),
    ("Chief Technology Officer", "Direttore Tecnologico"),
    ("Chief Executive Officer", "Amministratore Delegato"),
    ("Chief Operating Officer", "Direttore Operativo"),
    ("Chief Marketing Officer", "Direttore Marketing"),
    ("Digital Marketing Manager", "Responsabile Marketing Digitale"),
    ("SEO Specialist", "Specialista SEO"),
    ("SEM Specialist", "Specialista SEM"),
    ("Social Media Manager", "Social Media Manager"),
    ("Content Manager", "Content Manager"),
    ("Copywriter", "Copywriter"),
    ("Growth Hacker", "Growth Hacker"),
    ("Sales Manager", "Responsabile Vendite"),
    ("Account Manager", "Account Manager"),
    ("Business Development Manager", "Responsabile Sviluppo Business"),
    ("Sales Representative", "Rappresentante Commerciale"),
    ("Customer Success Manager", "Responsabile Customer Success"),
    ("Accountant", "Contabile"),
    ("Financial Analyst", "Analista Finanziario"),
    ("Controller", "Controller"),
    ("Investment Banker", "Investment Banker"),
    ("Auditor", "Revisore"),
    ("Risk Manager", "Risk Manager"),
    ("Legal Counsel", "Consulente Legale"),
    ("Corporate Lawyer", "Avvocato d'Impresa"),
    ("Compliance Officer", "Responsabile Compliance"),
    ("Medical Doctor", "Medico"),
    ("Nurse", "Infermiere"),
    ("Surgeon", "Chirurgo"),
    ("Psychologist", "Psicologo"),
    ("Physiotherapist", "Fisioterapista"),
    ("Pharmacist", "Farmacista"),
    ("Biologist", "Biologo"),
    ("Laboratory Technician", "Tecnico di Laboratorio"),
    ("Civil Engineer", "Ingegnere Civile"),
    ("Mechanical Engineer", "Ingegnere Meccanico"),
    ("Electrical Engineer", "Ingegnere Elettrico"),
    ("Electronics Engineer", "Ingegnere Elettronico"),
    ("Aerospace Engineer", "Ingegnere Aerospaziale"),
    ("Chemical Engineer", "Ingegnere Chimico"),
    ("Management Engineer", "Ingegnere Gestionale"),
    ("Energy Engineer", "Ingegnere Energetico"),
    ("Teacher", "Insegnante"),
    ("University Professor", "Professore Universitario"),
    ("Trainer", "Formatore"),
    ("Tutor", "Tutor"),
    ("Researcher", "Ricercatore"),
    ("Production Operator", "Operatore di Produzione"),
    ("Maintenance Technician", "Tecnico Manutentore"),
    ("Plant Manager", "Responsabile di Stabilimento"),
    ("Supply Chain Manager", "Responsabile Supply Chain"),
    ("Logistics Manager", "Responsabile Logistica"),
    ("Procurement Manager", "Responsabile Acquisti"),
    ("HR Manager", "Responsabile HR"),
    ("Recruiter", "Recruiter"),
    ("Talent Acquisition Specialist", "Specialista Talent Acquisition"),
    ("HR Business Partner", "HR Business Partner"),
    ("Compensation & Benefits Manager", "Responsabile Compensation & Benefits"),
    ("Journalist", "Giornalista"),
    ("Photographer", "Fotografo"),
    ("Videomaker", "Videomaker"),
    ("Director", "Regista"),
    ("Actor", "Attore"),
    ("Content Creator", "Content Creator"),
    ("Art Director", "Art Director"),
    ("Public Official", "Funzionario Pubblico"),
    ("Public Executive", "Dirigente Pubblico"),
    ("Diplomat", "Diplomatico"),
    ("Law Enforcement Officer", "Forze dell'Ordine"),
    ("Magistrate", "Magistrato"),
    ("Electrician", "Elettricista"),
    ("Plumber", "Idraulico"),
    ("Mason", "Muratore"),
    ("Carpenter", "Falegname"),
    ("Mechanic", "Meccanico"),
    ("IT Technician", "Tecnico Informatico"),
    ("Driver", "Autista"),
    ("Pilot", "Pilota"),
    ("Train Driver", "Macchinista Ferroviario"),
    ("Sailor", "Marinaio"),
    ("Logistician", "Logista"),
    ("Solutions Architect", "Solutions Architect"),
    ("Technical Architect", "Technical Architect"),
    ("Enterprise Architect", "Enterprise Architect"),
    ("Software Architect", "Software Architect"),
    ("Blockchain Developer", "Sviluppatore Blockchain"),
    ("AR Developer", "Sviluppatore AR"),
    ("VR Developer", "Sviluppatore VR"),
    ("Robotics Engineer", "Ingegnere Robotico"),
    ("Automation Engineer", "Ingegnere dell'Automazione"),
    ("Test Engineer", "Ingegnere di Test"),
    ("Release Manager", "Release Manager"),
    ("Build Engineer", "Build Engineer"),
    ("IT Manager", "Responsabile IT"),
    ("Help Desk Technician", "Tecnico Help Desk"),
    ("Database Administrator", "Amministratore Database"),
    ("Cloud Security Engineer", "Ingegnere Sicurezza Cloud"),
    ("Information Security Analyst", "Analista Sicurezza Informatica"),
    ("Digital Forensics Analyst", "Analista Digital Forensics"),
    ("Malware Analyst", "Analista Malware"),
    ("Security Consultant", "Consulente Sicurezza"),
    ("Technology Consultant", "Consulente Tecnologico"),
    ("SAP Consultant", "Consulente SAP"),
    ("ERP Consultant", "Consulente ERP"),
    ("CRM Consultant", "Consulente CRM"),
    ("Salesforce Administrator", "Amministratore Salesforce"),
    ("Salesforce Developer", "Sviluppatore Salesforce"),
    ("Shopify Developer", "Sviluppatore Shopify"),
    ("WordPress Developer", "Sviluppatore WordPress"),
    ("Web Designer", "Web Designer"),
    ("Email Marketing Specialist", "Specialista Email Marketing"),
    ("Affiliate Marketing Manager", "Responsabile Affiliate Marketing"),
    ("Media Planner", "Media Planner"),
    ("Brand Manager", "Brand Manager"),
    ("Product Marketing Manager", "Responsabile Product Marketing"),
    ("Market Research Analyst", "Analista di Mercato"),
    ("Public Relations Manager", "Responsabile Relazioni Pubbliche"),
    ("Event Manager", "Event Manager"),
    ("Community Manager", "Community Manager"),
    ("Partnership Manager", "Partnership Manager"),
    ("Inside Sales Representative", "Inside Sales Representative"),
    ("Technical Sales Engineer", "Ingegnere Tecnico Commerciale"),
    ("Pre-Sales Engineer", "Ingegnere Pre-Sales"),
    ("Real Estate Agent", "Agente Immobiliare"),
    ("Property Manager", "Property Manager"),
    ("Insurance Broker", "Broker Assicurativo"),
    ("Underwriter", "Underwriter"),
    ("Loan Officer", "Funzionario Prestiti"),
    ("Tax Consultant", "Consulente Fiscale"),
    ("Bookkeeper", "Addetto Contabile"),
    ("Treasury Analyst", "Analista Tesoreria"),
    ("Actuary", "Attuario"),
    ("Economist", "Economista"),
    ("Notary", "Notaio"),
    ("Paralegal", "Paralegal"),
    ("Legal Assistant", "Assistente Legale"),
    ("Judge", "Giudice"),
    ("Dentist", "Dentista"),
    ("Veterinarian", "Veterinario"),
    ("Midwife", "Ostetrica"),
    ("Dietitian", "Dietista"),
    ("Speech Therapist", "Logopedista"),
    ("Radiologist", "Radiologo"),
    ("Anesthesiologist", "Anestesista"),
    ("Professional Educator", "Educatore Professionale"),
    ("Social Worker", "Assistente Sociale"),
    ("Archaeologist", "Archeologo"),
    ("Librarian", "Bibliotecario"),
    ("Translator", "Traduttore"),
    ("Interpreter", "Interprete"),
    ("Tour Guide", "Guida Turistica"),
    ("Travel Agent", "Agente di Viaggio"),
    ("Hotel Manager", "Hotel Manager"),
    ("Receptionist", "Receptionist"),
    ("Chef", "Chef"),
    ("Sous Chef", "Sous Chef"),
    ("Pastry Chef", "Pasticcere"),
    ("Sommelier", "Sommelier"),
    ("Waiter", "Cameriere"),
    ("Barista", "Barista"),
    ("Bartender", "Barman"),
    ("Personal Trainer", "Personal Trainer"),
    ("Yoga Instructor", "Istruttore di Yoga"),
    ("Massage Therapist", "Massaggiatore"),
    ("Beautician", "Estetista"),
    ("Hairdresser", "Parrucchiere"),
    ("Make-up Artist", "Truccatore"),
    ("Interior Designer", "Interior Designer"),
    ("Landscape Designer", "Paesaggista"),
    ("Surveyor", "Geometra"),
    ("Industrial Expert", "Perito Industriale"),
    ("Cartographer", "Cartografo"),
    ("CNC Operator", "Operatore CNC"),
    ("Welder", "Saldatore"),
    ("Auto Body Technician", "Carrozziere"),
    ("Tire Technician", "Gommista"),
    ("Elevator Technician", "Ascensorista"),
    ("Refrigeration Technician", "Frigorista"),
    ("Antenna Technician", "Antennista"),
    ("Home Automation Technician", "Tecnico Domotica"),
]


def _merge_hard_skills():
    merged = {}

    for name, it_translation in BASE_HARD_SKILLS:
        merged[name] = it_translation

    for name, it_translation in REQUESTED_HARD_SKILLS:
        merged.setdefault(name, it_translation)

    return [(name, it_translation) for name, it_translation in merged.items()]


HARD_SKILLS = _merge_hard_skills()


SOFT_SKILLS = [
    ("Leadership", "Leadership"),
    ("Teamwork", "Lavoro di Squadra"),
    ("Communication", "Comunicazione"),
    ("Active Listening", "Ascolto Attivo"),
    ("Empathy", "Empatia"),
    ("Collaboration", "Collaborazione"),
    ("Conflict Resolution", "Risoluzione Conflitti"),
    ("Negotiation", "Negoziazione"),
    ("Problem Solving", "Risoluzione Problemi"),
    ("Critical Thinking", "Pensiero Critico"),
    ("Analytical Thinking", "Pensiero Analitico"),
    ("Creativity", "Creativita"),
    ("Innovation Mindset", "Mentalita Innovativa"),
    ("Adaptability", "Adattabilita"),
    ("Resilience", "Resilienza"),
    ("Stress Management", "Gestione dello Stress"),
    ("Time Management", "Gestione del Tempo"),
    ("Prioritization", "Definizione Priorita"),
    ("Decision Making", "Presa di Decisioni"),
    ("Accountability", "Responsabilita"),
    ("Ownership", "Senso di Responsabilita"),
    ("Initiative", "Intraprendenza"),
    ("Reliability", "Affidabilita"),
    ("Professional Ethics", "Etica Professionale"),
    ("Cultural Awareness", "Consapevolezza Culturale"),
    ("Intercultural Communication", "Comunicazione Interculturale"),
    ("Mentoring", "Mentoring"),
    ("Coaching", "Coaching"),
    ("Facilitation", "Facilitazione"),
    ("Public Speaking", "Parlare in Pubblico"),
    ("Presentation Skills", "Capacita di Presentazione"),
    ("Networking", "Networking"),
    ("Relationship Building", "Costruzione Relazioni"),
    ("Community Engagement", "Coinvolgimento della Comunita"),
    ("Service Orientation", "Orientamento al Servizio"),
    ("Strategic Thinking", "Pensiero Strategico"),
    ("Systems Thinking", "Pensiero Sistemico"),
    ("Learning Agility", "Agilita di Apprendimento"),
    ("Curiosity", "Curiosita"),
    ("Attention to Detail", "Attenzione ai Dettagli"),
    ("Organization", "Organizzazione"),
    ("Self Management", "Autogestione"),
    ("Emotional Intelligence", "Intelligenza Emotiva"),
    ("Patience", "Pazienza"),
    ("Diplomacy", "Diplomazia"),
]


class Command(BaseCommand):
    help = "Popola un catalogo esteso di Skill e SoftSkill senza duplicati."

    def add_arguments(self, parser):
        parser.add_argument(
            "--overwrite-translations",
            action="store_true",
            help="Sovrascrive sempre la traduzione italiana esistente.",
        )

    def handle(self, *args, **options):
        overwrite = options["overwrite_translations"]

        hard_created, hard_updated = self._upsert_items(
            model=Skill,
            items=HARD_SKILLS,
            overwrite=overwrite,
        )
        soft_created, soft_updated = self._upsert_items(
            model=SoftSkill,
            items=SOFT_SKILLS,
            overwrite=overwrite,
        )

        self.stdout.write(
            self.style.SUCCESS(
                "Seed completato: "
                f"Skill create={hard_created}, aggiornate={hard_updated}; "
                f"SoftSkill create={soft_created}, aggiornate={soft_updated}."
            )
        )

    def _upsert_items(self, model, items, overwrite=False):
        created_count = 0
        updated_count = 0

        for name, it_translation in items:
            obj, created = model.objects.get_or_create(name=name)
            translations = dict(obj.translations or {})

            if created:
                created_count += 1
            if overwrite or not translations.get("it"):
                translations["it"] = it_translation
                obj.translations = translations
                obj.save(update_fields=["translations"])
                if not created:
                    updated_count += 1

        return created_count, updated_count
