# Generated by Django 5.2.8 on 2025-11-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titolo della card', max_length=255, verbose_name='Titolo')),
                ('subtitle', models.CharField(help_text='Sottotitolo/descrizione breve', max_length=500, verbose_name='Sottotitolo')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version del titolo (generato automaticamente)', max_length=255, unique=True)),
                ('cover_image', models.ImageField(help_text='Immagine principale della card', upload_to='cards/covers/%Y/%m/', verbose_name='Immagine di copertina')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('content', models.TextField(help_text="Contenuto HTML dell'articolo", verbose_name='Contenuto')),
                ('date_type', models.CharField(choices=[('single', 'Data Singola'), ('range', 'Range di Date'), ('none', 'Nessuna Data')], default='single', max_length=10, verbose_name='Tipo di data')),
                ('date', models.DateField(blank=True, help_text="Data singola dell'evento", null=True, verbose_name='Data evento')),
                ('date_start', models.DateField(blank=True, help_text='Data inizio per eventi con range', null=True, verbose_name='Data inizio')),
                ('date_end', models.DateField(blank=True, help_text='Data fine per eventi con range', null=True, verbose_name='Data fine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
                ('is_published', models.BooleanField(default=False, help_text='La card è visibile pubblicamente', verbose_name='Pubblicato')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizzazioni')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Autore')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='section_car_created_e295fa_idx'), models.Index(fields=['slug'], name='section_car_slug_663e15_idx'), models.Index(fields=['is_published', '-created_at'], name='section_car_is_publ_f7bb61_idx')],
            },
        ),
    ]
