# Generated by Django 5.2.7 on 2026-09-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cards/gallery/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='file', max_length=10)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card Attachment',
                'verbose_name_plural': 'Card Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card Report',
                'verbose_name_plural': 'Card Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='articoli/%Y/%m/', verbose_name='file')),
                ('checksum', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='impronta')),
                ('width', models.PositiveIntegerField(verbose_name='larghezza')),
                ('height', models.PositiveIntegerField(verbose_name='altezza')),
                ('byte_size', models.PositiveIntegerField(verbose_name='peso in byte')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='testo alternativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'immagine',
                'verbose_name_plural': 'immagini',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='saved_at', verbose_name='Data salvataggio')),
            ],
            options={
                'verbose_name': 'Card Salvata',
                'verbose_name_plural': 'Card Salvate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Titolo della card', max_length=255, null=True, verbose_name='Titolo')),
                ('subtitle', models.CharField(blank=True, help_text='Sottotitolo/descrizione breve', max_length=500, null=True, verbose_name='Sottotitolo')),
                ('location', models.CharField(blank=True, help_text='Luogo o locazione della card', max_length=255, null=True, verbose_name='Localizzazione')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version del titolo (generato automaticamente)', max_length=255, unique=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Immagine principale della card', null=True, upload_to='cards/covers/%Y/%m/', verbose_name='Immagine di copertina')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('body', models.JSONField(blank=True, help_text="Documento strutturato dell'articolo", null=True, verbose_name='Corpo')),
                ('date_type', models.CharField(choices=[('single', 'Data Singola'), ('range', 'Range di Date'), ('none', 'Nessuna Data')], default='single', max_length=10, verbose_name='Tipo di data')),
                ('date', models.DateField(blank=True, help_text="Data singola dell'evento", null=True, verbose_name='Data evento')),
                ('date_start', models.DateField(blank=True, help_text='Data inizio per eventi con range', null=True, verbose_name='Data inizio')),
                ('date_end', models.DateField(blank=True, help_text='Data fine per eventi con range', null=True, verbose_name='Data fine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
                ('source_locale', models.CharField(db_index=True, default='it', max_length=10, verbose_name='lingua di stesura')),
                ('is_published', models.BooleanField(default=True, help_text='La card è visibile pubblicamente', verbose_name='Pubblicato')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizzazioni')),
                ('info_values', models.JSONField(blank=True, default=dict, help_text='Mappa chiave -> valore degli elementi informativi.', verbose_name='valori informativi')),
                ('article_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cms.articletype', verbose_name='tipo di articolo')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
