# Generated by Django 5.2.8 on 2026-01-20 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, choices=[('storie-e-radici', 'Storie e Radici'), ('scopri-la-calabria', 'Scopri la Calabria'), ('scambi-e-mobilita', 'Scambi e Mobilità'), ('adotta-un-progetto', 'Adotta un Progetto'), ('eccellenze-calabresi', 'Eccellenze Calabresi'), ('calendario-delle-radici', 'Calendario delle Radici'), ('archivio', 'Archivio')], max_length=30, null=True, verbose_name='Sezione')),
                ('tab', models.CharField(blank=True, help_text="Tab specifica all'interno della sezione", max_length=100, null=True, verbose_name='Tab')),
                ('title', models.CharField(blank=True, help_text='Titolo della card', max_length=255, null=True, verbose_name='Titolo')),
                ('subtitle', models.CharField(blank=True, help_text='Sottotitolo/descrizione breve', max_length=500, null=True, verbose_name='Sottotitolo')),
                ('location', models.CharField(blank=True, help_text='Luogo o locazione della card', max_length=255, null=True, verbose_name='Localizzazione')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version del titolo (generato automaticamente)', max_length=255, unique=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Immagine principale della card', null=True, upload_to='cards/covers/%Y/%m/', verbose_name='Immagine di copertina')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('content', models.TextField(blank=True, help_text="Contenuto HTML dell'articolo", null=True, verbose_name='Contenuto')),
                ('date_type', models.CharField(choices=[('single', 'Data Singola'), ('range', 'Range di Date'), ('none', 'Nessuna Data')], default='single', max_length=10, verbose_name='Tipo di data')),
                ('date', models.DateField(blank=True, help_text="Data singola dell'evento", null=True, verbose_name='Data evento')),
                ('date_start', models.DateField(blank=True, help_text='Data inizio per eventi con range', null=True, verbose_name='Data inizio')),
                ('date_end', models.DateField(blank=True, help_text='Data fine per eventi con range', null=True, verbose_name='Data fine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
                ('is_published', models.BooleanField(default=True, help_text='La card è visibile pubblicamente', verbose_name='Pubblicato')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizzazioni')),
                ('infoElementValues', models.JSONField(blank=True, default=list, help_text='Array di valori per gli elementi info (uno per ogni tupla della sezione/tab)', null=True, verbose_name='Info Element Values')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Autore')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cards/gallery/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='file', max_length=10)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='section.card')),
            ],
            options={
                'verbose_name': 'Card Attachment',
                'verbose_name_plural': 'Card Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='section.card')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Report',
                'verbose_name_plural': 'Card Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(max_length=10)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_subtitle', models.TextField(blank=True)),
                ('translated_content', models.TextField(blank=True)),
                ('provider', models.CharField(choices=[('deepl', 'DeepL'), ('google', 'Google Cloud Translation')], max_length=20)),
                ('detected_source_language', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='section.card')),
            ],
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['-created_at'], name='section_car_created_e295fa_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['slug'], name='section_car_slug_663e15_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['is_published', '-created_at'], name='section_car_is_publ_f7bb61_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtranslation',
            index=models.Index(fields=['card', 'target_language'], name='section_car_card_id_834a62_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtranslation',
            index=models.Index(fields=['target_language'], name='section_car_target__fdeaf6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardtranslation',
            unique_together={('card', 'target_language')},
        ),
    ]
