# Generated by Django 5.2.7 on 2026-09-21 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('section', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Autore'),
        ),
        migrations.AddField(
            model_name='card',
            name='geo_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cms.geoarea', verbose_name='area geografica'),
        ),
        migrations.AddField(
            model_name='cardattachment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='section.card'),
        ),
        migrations.AddField(
            model_name='cardreport',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='section.card'),
        ),
        migrations.AddField(
            model_name='cardreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to=settings.AUTH_USER_MODEL, verbose_name='caricata da'),
        ),
        migrations.AddField(
            model_name='savedcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='section.card', verbose_name='Card'),
        ),
        migrations.AddField(
            model_name='savedcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['-created_at'], name='section_car_created_e295fa_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['slug'], name='section_car_slug_663e15_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['is_published', '-created_at'], name='section_car_is_publ_f7bb61_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcard',
            index=models.Index(fields=['user', '-created_at'], name='section_sav_user_id_2c8e36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedcard',
            unique_together={('user', 'card')},
        ),
    ]
