# Generated by Django 5.2.8 on 2025-11-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_published',
            field=models.BooleanField(default=True, help_text='La card è visibile pubblicamente', verbose_name='Pubblicato'),
        ),
    ]
