# Generated by ChatGPT on 2026-01-20
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cards/gallery/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='file', max_length=10)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='section.card')),
            ],
            options={
                'verbose_name': 'Card Attachment',
                'verbose_name_plural': 'Card Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='section.card')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Report',
                'verbose_name_plural': 'Card Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(max_length=10)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_subtitle', models.TextField(blank=True)),
                ('translated_content', models.TextField(blank=True)),
                ('provider', models.CharField(choices=[('deepl', 'DeepL'), ('google', 'Google Cloud Translation')], max_length=20)),
                ('detected_source_language', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='section.card')),
            ],
            options={
                'unique_together': {('card', 'target_language')},
            },
        ),
        migrations.AddIndex(
            model_name='cardtranslation',
            index=models.Index(fields=['card', 'target_language'], name='section_car_card_id_32b640_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtranslation',
            index=models.Index(fields=['target_language'], name='section_car_target__9a3122_idx'),
        ),
    ]
