# Generated by Django 5.2.7 on 2026-02-13 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_add_contact_to_eccellenze_calabresi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data salvataggio')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='section.card', verbose_name='Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Card Salvata',
                'verbose_name_plural': 'Card Salvate',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='section_sav_user_id_d27a5b_idx')],
                'unique_together': {('user', 'card')},
            },
        ),
    ]
