# Generated by Django 5.2.8 on 2025-11-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_alter_card_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='section',
            field=models.CharField(choices=[('storie-e-radici', 'Storie e Radici'), ('scopri-la-calabria', 'Scopri la Calabria'), ('scambi-e-mobilita', 'Scambi e Mobilità'), ('adotta-un-progetto', 'Adotta un Progetto'), ('partner-e-collaborazioni', 'Partner e Collaborazioni'), ('eccellenze-calabresi', 'Eccellenze Calabresi'), ('cip', 'CIP')], default='storie-e-radici', max_length=30, verbose_name='Sezione'),
        ),
    ]
