# Generated by Django 5.2.7 on 2026-02-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_savedcard'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedcard',
            new_name='section_sav_user_id_2c8e36_idx',
            old_name='section_sav_user_id_d27a5b_idx',
        ),
        migrations.AlterField(
            model_name='savedcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='saved_at', verbose_name='Data salvataggio'),
        ),
    ]
