# Generated by Django 5.2.8 on 2025-12-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_alter_card_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_event',
            field=models.BooleanField(default=False, help_text='Indica se la card rappresenta un evento', verbose_name='È un evento'),
        ),
    ]
