# Generated by Django 5.2.8 on 2026-09-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_fix_savedcard_column_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtranslation',
            name='translated_title',
            field=models.TextField(),
        ),
    ]
