# Generated by Django 5.2.8 on 2025-12-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_card_is_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='section',
            field=models.CharField(choices=[('storie-e-radici', 'Storie e Radici'), ('scopri-la-calabria', 'Scopri la Calabria'), ('scambi-e-mobilita', 'Scambi e Mobilità'), ('adotta-un-progetto', 'Adotta un Progetto'), ('partner-e-collaborazioni', 'Partner e Collaborazioni'), ('eccellenze-calabresi', 'Eccellenze Calabresi'), ('eventi', 'Eventi')], default='storie-e-radici', max_length=30, verbose_name='Sezione'),
        ),
    ]
