# Generated by Django 5.2.7 on 2026-09-01 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_articletype_articletypeinfoelement_articletypetag_and_more'),
        ('section', '0005_alter_cardtranslation_translated_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='article_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cms.articletype', verbose_name='tipo di articolo'),
        ),
        migrations.AddField(
            model_name='card',
            name='info_values',
            field=models.JSONField(blank=True, default=dict, help_text='Mappa chiave -> valore degli elementi informativi.', verbose_name='valori informativi'),
        ),
    ]
