# Generated by Django 5.2.7 on 2026-09-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_geoarea'),
        ('section', '0006_card_article_type_card_info_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='geo_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cms.geoarea', verbose_name='area geografica'),
        ),
    ]
