# Generated by Django 5.2.8 on 2025-12-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0006_alter_card_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_event',
        ),
        migrations.AddField(
            model_name='card',
            name='infoElementValues',
            field=models.JSONField(blank=True, default=list, help_text='Array di valori per gli elementi info (uno per ogni tupla della sezione/tab)', null=True, verbose_name='Info Element Values'),
        ),
        migrations.AddField(
            model_name='card',
            name='tab',
            field=models.CharField(blank=True, help_text="Tab specifica all'interno della sezione", max_length=100, null=True, verbose_name='Tab'),
        ),
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(blank=True, help_text="Contenuto HTML dell'articolo", null=True, verbose_name='Contenuto'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Immagine principale della card', null=True, upload_to='cards/covers/%Y/%m/', verbose_name='Immagine di copertina'),
        ),
        migrations.AlterField(
            model_name='card',
            name='section',
            field=models.CharField(blank=True, choices=[('storie-e-radici', 'Storie e Radici'), ('scopri-la-calabria', 'Scopri la Calabria'), ('scambi-e-mobilita', 'Scambi e Mobilità'), ('adotta-un-progetto', 'Adotta un Progetto'), ('partner-e-collaborazioni', 'Partner e Collaborazioni'), ('eccellenze-calabresi', 'Eccellenze Calabresi'), ('eventi', 'Eventi')], max_length=30, null=True, verbose_name='Sezione'),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Sottotitolo/descrizione breve', max_length=500, null=True, verbose_name='Sottotitolo'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, help_text='Titolo della card', max_length=255, null=True, verbose_name='Titolo'),
        ),
    ]
