# Generated by Django 5.2.8 on 2025-12-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_remove_card_is_event_card_infoelementvalues_card_tab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='location',
            field=models.CharField(blank=True, help_text='Luogo o locazione della card', max_length=255, null=True, verbose_name='Localizzazione'),
        ),
        migrations.AlterField(
            model_name='card',
            name='section',
            field=models.CharField(blank=True, choices=[('storie-e-radici', 'Storie e Radici'), ('scopri-la-calabria', 'Scopri la Calabria'), ('scambi-e-mobilita', 'Scambi e Mobilità'), ('adotta-un-progetto', 'Adotta un Progetto'), ('eccellenze-calabresi', 'Eccellenze Calabresi'), ('calendario-delle-radici', 'Calendario delle Radici'), ('archivio', 'Archivio')], max_length=30, null=True, verbose_name='Sezione'),
        ),
    ]
