# Generated by Django 5.2.7 on 2026-09-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_card_geo_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='infoElementValues',
        ),
        migrations.RemoveField(
            model_name='card',
            name='section',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tab',
        ),
    ]
