# Generated by Django 5.2.7 on 2026-09-17 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0008_remove_card_infoelementvalues_remove_card_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='content',
        ),
        migrations.AddField(
            model_name='card',
            name='body',
            field=models.JSONField(blank=True, help_text="Documento strutturato dell'articolo", null=True, verbose_name='Corpo'),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='articoli/%Y/%m/', verbose_name='file')),
                ('checksum', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='impronta')),
                ('width', models.PositiveIntegerField(verbose_name='larghezza')),
                ('height', models.PositiveIntegerField(verbose_name='altezza')),
                ('byte_size', models.PositiveIntegerField(verbose_name='peso in byte')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='testo alternativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to=settings.AUTH_USER_MODEL, verbose_name='caricata da')),
            ],
            options={
                'verbose_name': 'immagine',
                'verbose_name_plural': 'immagini',
                'ordering': ['-created_at'],
            },
        ),
    ]
