# Generated by Django 5.2.7 on 2026-01-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_card_attachments_reports_translations'),
        ('section', '0008_card_location_alter_card_section'),
    ]

    operations = [
    ]
