# Generated by Django 5.2.7 on 2026-09-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0009_corpo_strutturato_e_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtranslation',
            name='translated_content',
        ),
        migrations.AddField(
            model_name='card',
            name='source_locale',
            field=models.CharField(db_index=True, default='it', max_length=10, verbose_name='lingua di stesura'),
        ),
        migrations.AddField(
            model_name='cardtranslation',
            name='human_locked',
            field=models.BooleanField(default=False, verbose_name='corretta a mano'),
        ),
        migrations.AddField(
            model_name='cardtranslation',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, verbose_name='da rivedere'),
        ),
        migrations.AddField(
            model_name='cardtranslation',
            name='translated_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardtranslation',
            name='translated_info_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cardtranslation',
            name='translated_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cardtranslation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cardtranslation',
            name='provider',
            field=models.CharField(choices=[('claude', 'Modello linguistico'), ('deepl', 'DeepL'), ('google', 'Google Cloud Translation'), ('identita', 'Nessuna traduzione (testo originale)'), ('umano', 'Scritta da una persona')], max_length=20),
        ),
    ]
