# Generated by Django 5.2.7 on 2026-01-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0009_merge_20260120_1425'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cardtranslation',
            new_name='section_car_card_id_834a62_idx',
            old_name='section_car_card_id_32b640_idx',
        ),
        migrations.RenameIndex(
            model_name='cardtranslation',
            new_name='section_car_target__fdeaf6_idx',
            old_name='section_car_target__9a3122_idx',
        ),
    ]
