# Generated by Django 5.2.7 on 2026-09-18 14:55

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import taggit.managers
import uuid
import wagtail.fields
import wagtail.images.models
import wagtail.models.media
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('width', models.IntegerField(editable=False, verbose_name='width')),
                ('height', models.IntegerField(editable=False, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=40)),
                ('credit', models.CharField(blank=True, max_length=255, verbose_name='crediti')),
            ],
            options={
                'verbose_name': 'immagine',
                'verbose_name_plural': 'immagini',
                'abstract': False,
            },
            bases=(wagtail.images.models.ImageFileMixin, modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CMSRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
            ],
            bases=(wagtail.images.models.ImageFileMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('country', 'Nazione'), ('region', 'Regione'), ('province', 'Provincia'), ('city', 'Comune')], max_length=12, verbose_name='livello')),
                ('key', models.SlugField(max_length=80, verbose_name='chiave')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Nomi in altre lingue, es. {"en": "Apulia"}. Se manca si usa il nome italiano.', verbose_name='traduzioni')),
                ('code', models.CharField(blank=True, help_text='Sigla della provincia (BA, MI) o codice della nazione (IT).', max_length=8, verbose_name='sigla')),
                ('path', models.CharField(db_index=True, editable=False, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='attiva')),
            ],
            options={
                'verbose_name': 'area geografica',
                'verbose_name_plural': 'aree geografiche',
                'ordering': ['path'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 6), ('split_hero', 22), ('rich_text', 23), ('icon_card_grid', 31), ('explanation_steps', 37), ('numbered_steps', 41), ('section_tiles', 46), ('stats_bar', 51), ('partner_grid', 60), ('quote', 65), ('text_band', 67), ('task_list', 73), ('people_grid', 81), ('credit', 86), ('tier_cards', 90), ('cta_banner', 92), ('article_list', 99), ('tabbed_article_list', 103), ('image', 104)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'titolo'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'descrizione'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'La pillola sopra il titolo.', 'label': 'etichetta', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'Bianco'), ('light', 'Grigio chiaro'), ('brand-primary', 'Blu istituzionale'), ('brand-secondary', 'Giallo istituzionale'), ('brand-gradient', 'Sfumatura istituzionale'), ('section', 'Colore della sezione')], 'label': 'sfondo'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('brand-primary', 'Blu istituzionale'), ('brand-secondary', 'Giallo'), ('emerald', 'Verde'), ('amber', 'Ambra'), ('rose', 'Rosa'), ('sky', 'Azzurro'), ('teal', 'Turchese'), ('stone', 'Marrone'), ('slate', 'Grigio')], 'help_text': "Usato solo se lo sfondo e' 'Colore della sezione'.", 'label': 'colore della sezione'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Identificativo del blocco a cui portare l'utente. Lascia vuoto per non mostrare la freccia.", 'label': 'scorri fino a', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('tag', 2), ('surface', 3), ('accent', 4), ('scroll_to_id', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'La targhetta sopra al titolo.', 'label': 'pillola', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Seconda riga, in giallo.', 'label': 'titolo evidenziato', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'sottotitolo', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'titolo del riquadro', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Righe vuote separano i paragrafi.', 'label': 'testo del riquadro', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'etichetta', 'required': False}), 13: ('wagtail.blocks.PageChooserBlock', (), {'label': 'pagina del sito', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es. /rota-space', 'label': 'percorso interno', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'indirizzo esterno', 'required': False}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('always', 'Sempre'), ('authenticated', 'Solo a chi ha fatto accesso'), ('anonymous', 'Solo a chi non ha fatto accesso')], 'help_text': 'Un "Iscriviti" non ha senso per chi ha gia\' un account.', 'label': 'a chi si mostra'}), 17: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'pulsante principale', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'pulsante secondario', 'required': False}), 19: ('wagtail.blocks.URLBlock', (), {'label': 'video', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'titolo del video', 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'sottotitolo del video', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('pill', 7), ('title_top', 0), ('title_highlight', 8), ('subtitle', 9), ('note_title', 10), ('note_body', 11), ('primary_cta', 17), ('secondary_cta', 18), ('video_url', 19), ('video_title', 20), ('video_subtitle', 21)]], {}), 23: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'blockquote'], 'label': 'testo'}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'titolo', 'required': False}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], 'label': 'colonne'}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Award', 'Award'), ('Bookmark', 'Bookmark'), ('Calendar', 'Calendar'), ('Clock', 'Clock'), ('Compass', 'Compass'), ('DollarSign', 'DollarSign'), ('Flag', 'Flag'), ('Globe', 'Globe'), ('Heart', 'Heart'), ('Mail', 'Mail'), ('MapPin', 'MapPin'), ('Phone', 'Phone'), ('Star', 'Star'), ('Tag', 'Tag'), ('Target', 'Target'), ('TrendingUp', 'TrendingUp'), ('Users', 'Users'), ('Utensils', 'Utensils'), ('Camera', 'Camera'), ('BookOpen', 'BookOpen'), ('Handshake', 'Handshake'), ('Lightbulb', 'Lightbulb'), ('Leaf', 'Leaf'), ('Music', 'Music'), ('Info', 'Info'), ('Code', 'Code')], 'label': 'icona'}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('brand-primary', 'Blu istituzionale'), ('brand-secondary', 'Giallo'), ('emerald', 'Verde'), ('amber', 'Ambra'), ('rose', 'Rosa'), ('sky', 'Azzurro'), ('teal', 'Turchese'), ('stone', 'Marrone'), ('slate', 'Grigio')], 'label': 'accento'}), 28: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'collegamento', 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('icon', 26), ('title', 0), ('description', 1), ('accent', 27), ('cta', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'label': 'schede'}), 31: ('wagtail.blocks.StructBlock', [[('title', 24), ('subtitle', 9), ('columns', 25), ('surface', 3), ('items', 30)]], {}), 32: ('wagtail.blocks.TextBlock', (), {'label': 'descrizione', 'required': False}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('brand-primary', 'Blu istituzionale'), ('brand-secondary', 'Giallo'), ('emerald', 'Verde'), ('amber', 'Ambra'), ('rose', 'Rosa'), ('sky', 'Azzurro'), ('teal', 'Turchese'), ('stone', 'Marrone'), ('slate', 'Grigio')], 'label': 'colore'}), 34: ('wagtail.blocks.EmailBlock', (), {'label': 'email di contatto', 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('icon', 26), ('title', 0), ('description', 1)]], {}), 36: ('wagtail.blocks.ListBlock', (35,), {'label': 'passi'}), 37: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 32), ('accent', 33), ('contact_email', 34), ('steps', 36)]], {}), 38: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {}), 39: ('wagtail.blocks.ListBlock', (38,), {'label': 'passi'}), 40: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'invito all azione', 'required': False}), 41: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 9), ('surface', 3), ('steps', 39), ('cta', 40)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'label': 'etichetta'}), 43: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'destinazione'}), 44: ('wagtail.blocks.StructBlock', [[('icon', 26), ('label', 42), ('accent', 33), ('link', 43)]], {}), 45: ('wagtail.blocks.ListBlock', (44,), {'label': 'riquadri'}), 46: ('wagtail.blocks.StructBlock', [[('title', 24), ('subtitle', 9), ('columns', 25), ('surface', 3), ('tiles', 45)]], {}), 47: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('clubs', 'Club'), ('rotarians', 'Rotariani'), ('countries', 'Paesi'), ('projects', 'Progetti')], 'label': 'dato'}), 48: ('wagtail.blocks.CharBlock', (), {'help_text': 'Mostrato se il dato non arriva.', 'label': 'valore di ripiego', 'required': False}), 49: ('wagtail.blocks.StructBlock', [[('source', 47), ('label', 42), ('fallback', 48)]], {}), 50: ('wagtail.blocks.ListBlock', (49,), {'label': 'numeri'}), 51: ('wagtail.blocks.StructBlock', [[('surface', 3), ('items', 50)]], {}), 52: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3'), ('4', '4')], 'label': 'colonne'}), 53: ('wagtail.blocks.CharBlock', (), {'label': 'nome'}), 54: ('cms.blocks.common.ImmagineBlock', (), {'label': 'logo', 'required': False}), 55: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternativa al logo per chi non ne ha uno.', 'label': 'emoji', 'max_length': 8, 'required': False}), 56: ('wagtail.blocks.URLBlock', (), {'label': 'sito', 'required': False}), 57: ('wagtail.blocks.IntegerBlock', (), {'default': 100, 'help_text': 'Alcuni loghi hanno molto spazio bianco intorno e vanno ingranditi per pesare come gli altri.', 'label': 'dimensione del logo (%)', 'max_value': 160, 'min_value': 60}), 58: ('wagtail.blocks.StructBlock', [[('name', 53), ('description', 32), ('logo', 54), ('emoji', 55), ('link', 56), ('logo_scale', 57)]], {}), 59: ('wagtail.blocks.ListBlock', (58,), {'label': 'partner'}), 60: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 32), ('columns', 52), ('surface', 3), ('items', 59)]], {}), 61: ('wagtail.blocks.TextBlock', (), {'label': 'citazione'}), 62: ('wagtail.blocks.CharBlock', (), {'label': 'autore', 'required': False}), 63: ('wagtail.blocks.CharBlock', (), {'label': 'ruolo', 'required': False}), 64: ('wagtail.blocks.CharBlock', (), {'label': 'luogo e data', 'required': False}), 65: ('wagtail.blocks.StructBlock', [[('quote', 61), ('author', 62), ('role', 63), ('place_and_date', 64)]], {}), 66: ('wagtail.blocks.TextBlock', (), {'label': 'testo'}), 67: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 66), ('surface', 3)]], {}), 68: ('wagtail.blocks.CharBlock', (), {'label': 'voce'}), 69: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'approfondimento', 'required': False}), 70: ('wagtail.blocks.StructBlock', [[('title', 68), ('link', 69)]], {}), 71: ('wagtail.blocks.ListBlock', (70,), {'label': 'voci'}), 72: ('wagtail.blocks.TextBlock', (), {'label': 'nota finale', 'required': False}), 73: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 9), ('items', 71), ('note', 72), ('surface', 3)]], {}), 74: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', '1'), ('2', '2'), ('3', '3')], 'label': 'colonne'}), 75: ('wagtail.blocks.EmailBlock', (), {'label': 'email', 'required': False}), 76: ('cms.blocks.common.ImmagineBlock', (), {'label': 'foto', 'required': False}), 77: ('wagtail.blocks.CharBlock', (), {'label': 'area'}), 78: ('wagtail.blocks.ListBlock', (77,), {'help_text': 'Es. i paesi seguiti da un referente.', 'label': 'aree di competenza', 'required': False}), 79: ('wagtail.blocks.StructBlock', [[('name', 53), ('role', 63), ('email', 75), ('photo', 76), ('areas', 78)]], {}), 80: ('wagtail.blocks.ListBlock', (79,), {'label': 'persone'}), 81: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 32), ('columns', 74), ('surface', 3), ('items', 80)]], {}), 82: ('wagtail.blocks.CharBlock', (), {'help_text': 'Sopra al riquadro. Es. Sviluppo tecnico', 'label': 'titolo', 'required': False}), 83: ('wagtail.blocks.CharBlock', (), {'label': 'sottotitolo', 'required': False}), 84: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es. Tech Solutions by', 'label': 'azienda', 'required': False}), 85: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'sito', 'required': False}), 86: ('wagtail.blocks.StructBlock', [[('heading', 82), ('subheading', 83), ('icon', 26), ('label', 84), ('name', 53), ('link', 85), ('surface', 3)]], {}), 87: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bronze', 'Bronzo'), ('silver', 'Argento'), ('gold', 'Oro')], 'label': 'livello'}), 88: ('wagtail.blocks.StructBlock', [[('tier', 87), ('title', 0), ('description', 1)]], {}), 89: ('wagtail.blocks.ListBlock', (88,), {'label': 'livelli'}), 90: ('wagtail.blocks.StructBlock', [[('title', 24), ('subtitle', 9), ('surface', 3), ('items', 89)]], {}), 91: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'pulsante principale'}), 92: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 32), ('surface', 3), ('primary_cta', 91), ('secondary_cta', 18)]], {}), 93: ('cms.blocks.common.TipoArticoloBlock', (), {'label': 'tipo di articolo'}), 94: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid', 'Griglia'), ('calendar', 'Calendario'), ('list', 'Elenco')], 'label': 'visualizzazione'}), 95: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Vuoto per mostrarli tutti.', 'label': 'quanti al massimo', 'max_value': 100, 'min_value': 1, 'required': False}), 96: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'campo di ricerca', 'required': False}), 97: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'filtro per tag', 'required': False}), 98: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'filtro geografico', 'required': False}), 99: ('wagtail.blocks.StructBlock', [[('heading', 24), ('article_type', 93), ('accent', 33), ('layout', 94), ('columns', 25), ('limit', 95), ('show_search', 96), ('show_tag_filter', 97), ('show_geo_filter', 98)]], {}), 100: ('wagtail.blocks.CharBlock', (), {'label': 'etichetta del tab'}), 101: ('wagtail.blocks.StructBlock', [[('label', 100), ('article_type', 93), ('layout', 94), ('columns', 25)]], {}), 102: ('wagtail.blocks.ListBlock', (101,), {'label': 'tab'}), 103: ('wagtail.blocks.StructBlock', [[('heading', 24), ('accent', 33), ('tabs', 102), ('show_search', 96), ('show_tag_filter', 97), ('show_geo_filter', 98)]], {}), 104: ('cms.blocks.common.ImmagineBlock', (), {'label': 'immagine'})}, verbose_name='contenuto')),
            ],
            options={
                'verbose_name': 'home page',
                'verbose_name_plural': 'home page',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('key', models.SlugField(help_text='Identificatore usato dal frontend. Non cambiarlo se il menu e gia in uso.', max_length=64, verbose_name='chiave')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, help_text='A cosa serve questo menu e dove compare.', verbose_name='descrizione')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menu',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=120, verbose_name='etichetta')),
                ('route', models.CharField(blank=True, help_text="Una rotta dell'applicazione, es. /rota-space. Serve per le pagine che restano codice.", max_length=200, verbose_name='percorso interno')),
                ('external_url', models.URLField(blank=True, verbose_name='indirizzo esterno')),
                ('icon', models.CharField(blank=True, choices=[('Award', 'Award'), ('Bookmark', 'Bookmark'), ('Calendar', 'Calendar'), ('Clock', 'Clock'), ('Compass', 'Compass'), ('DollarSign', 'DollarSign'), ('Flag', 'Flag'), ('Globe', 'Globe'), ('Heart', 'Heart'), ('Mail', 'Mail'), ('MapPin', 'MapPin'), ('Phone', 'Phone'), ('Star', 'Star'), ('Tag', 'Tag'), ('Target', 'Target'), ('TrendingUp', 'TrendingUp'), ('Users', 'Users'), ('Utensils', 'Utensils'), ('Camera', 'Camera'), ('BookOpen', 'BookOpen'), ('Handshake', 'Handshake'), ('Lightbulb', 'Lightbulb'), ('Leaf', 'Leaf'), ('Music', 'Music'), ('Info', 'Info'), ('Code', 'Code')], max_length=40, verbose_name='icona')),
                ('visibility', models.CharField(choices=[('always', 'Sempre'), ('authenticated', 'Solo a chi ha fatto accesso'), ('anonymous', 'Solo a chi non ha fatto accesso')], default='always', max_length=16, verbose_name='visibile')),
                ('roles', models.JSONField(blank=True, default=list, help_text='Lascia vuoto per mostrarla a tutti.', verbose_name='solo per questi ruoli')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='apri in una nuova scheda')),
            ],
            options={
                'verbose_name': 'voce di menu',
                'verbose_name_plural': 'voci di menu',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 6), ('split_hero', 22), ('rich_text', 23), ('icon_card_grid', 31), ('explanation_steps', 37), ('numbered_steps', 41), ('section_tiles', 46), ('stats_bar', 51), ('partner_grid', 60), ('quote', 65), ('text_band', 67), ('task_list', 73), ('people_grid', 81), ('credit', 86), ('tier_cards', 90), ('cta_banner', 92), ('article_list', 99), ('tabbed_article_list', 103), ('image', 104)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'titolo'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'descrizione'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'La pillola sopra il titolo.', 'label': 'etichetta', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'Bianco'), ('light', 'Grigio chiaro'), ('brand-primary', 'Blu istituzionale'), ('brand-secondary', 'Giallo istituzionale'), ('brand-gradient', 'Sfumatura istituzionale'), ('section', 'Colore della sezione')], 'label': 'sfondo'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('brand-primary', 'Blu istituzionale'), ('brand-secondary', 'Giallo'), ('emerald', 'Verde'), ('amber', 'Ambra'), ('rose', 'Rosa'), ('sky', 'Azzurro'), ('teal', 'Turchese'), ('stone', 'Marrone'), ('slate', 'Grigio')], 'help_text': "Usato solo se lo sfondo e' 'Colore della sezione'.", 'label': 'colore della sezione'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Identificativo del blocco a cui portare l'utente. Lascia vuoto per non mostrare la freccia.", 'label': 'scorri fino a', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('tag', 2), ('surface', 3), ('accent', 4), ('scroll_to_id', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'La targhetta sopra al titolo.', 'label': 'pillola', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Seconda riga, in giallo.', 'label': 'titolo evidenziato', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'sottotitolo', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'titolo del riquadro', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Righe vuote separano i paragrafi.', 'label': 'testo del riquadro', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'etichetta', 'required': False}), 13: ('wagtail.blocks.PageChooserBlock', (), {'label': 'pagina del sito', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es. /rota-space', 'label': 'percorso interno', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'indirizzo esterno', 'required': False}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('always', 'Sempre'), ('authenticated', 'Solo a chi ha fatto accesso'), ('anonymous', 'Solo a chi non ha fatto accesso')], 'help_text': 'Un "Iscriviti" non ha senso per chi ha gia\' un account.', 'label': 'a chi si mostra'}), 17: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'pulsante principale', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'pulsante secondario', 'required': False}), 19: ('wagtail.blocks.URLBlock', (), {'label': 'video', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'titolo del video', 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'sottotitolo del video', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('pill', 7), ('title_top', 0), ('title_highlight', 8), ('subtitle', 9), ('note_title', 10), ('note_body', 11), ('primary_cta', 17), ('secondary_cta', 18), ('video_url', 19), ('video_title', 20), ('video_subtitle', 21)]], {}), 23: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'blockquote'], 'label': 'testo'}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'titolo', 'required': False}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], 'label': 'colonne'}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Award', 'Award'), ('Bookmark', 'Bookmark'), ('Calendar', 'Calendar'), ('Clock', 'Clock'), ('Compass', 'Compass'), ('DollarSign', 'DollarSign'), ('Flag', 'Flag'), ('Globe', 'Globe'), ('Heart', 'Heart'), ('Mail', 'Mail'), ('MapPin', 'MapPin'), ('Phone', 'Phone'), ('Star', 'Star'), ('Tag', 'Tag'), ('Target', 'Target'), ('TrendingUp', 'TrendingUp'), ('Users', 'Users'), ('Utensils', 'Utensils'), ('Camera', 'Camera'), ('BookOpen', 'BookOpen'), ('Handshake', 'Handshake'), ('Lightbulb', 'Lightbulb'), ('Leaf', 'Leaf'), ('Music', 'Music'), ('Info', 'Info'), ('Code', 'Code')], 'label': 'icona'}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('brand-primary', 'Blu istituzionale'), ('brand-secondary', 'Giallo'), ('emerald', 'Verde'), ('amber', 'Ambra'), ('rose', 'Rosa'), ('sky', 'Azzurro'), ('teal', 'Turchese'), ('stone', 'Marrone'), ('slate', 'Grigio')], 'label': 'accento'}), 28: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'collegamento', 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('icon', 26), ('title', 0), ('description', 1), ('accent', 27), ('cta', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'label': 'schede'}), 31: ('wagtail.blocks.StructBlock', [[('title', 24), ('subtitle', 9), ('columns', 25), ('surface', 3), ('items', 30)]], {}), 32: ('wagtail.blocks.TextBlock', (), {'label': 'descrizione', 'required': False}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('brand-primary', 'Blu istituzionale'), ('brand-secondary', 'Giallo'), ('emerald', 'Verde'), ('amber', 'Ambra'), ('rose', 'Rosa'), ('sky', 'Azzurro'), ('teal', 'Turchese'), ('stone', 'Marrone'), ('slate', 'Grigio')], 'label': 'colore'}), 34: ('wagtail.blocks.EmailBlock', (), {'label': 'email di contatto', 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('icon', 26), ('title', 0), ('description', 1)]], {}), 36: ('wagtail.blocks.ListBlock', (35,), {'label': 'passi'}), 37: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 32), ('accent', 33), ('contact_email', 34), ('steps', 36)]], {}), 38: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {}), 39: ('wagtail.blocks.ListBlock', (38,), {'label': 'passi'}), 40: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'invito all azione', 'required': False}), 41: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 9), ('surface', 3), ('steps', 39), ('cta', 40)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'label': 'etichetta'}), 43: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'destinazione'}), 44: ('wagtail.blocks.StructBlock', [[('icon', 26), ('label', 42), ('accent', 33), ('link', 43)]], {}), 45: ('wagtail.blocks.ListBlock', (44,), {'label': 'riquadri'}), 46: ('wagtail.blocks.StructBlock', [[('title', 24), ('subtitle', 9), ('columns', 25), ('surface', 3), ('tiles', 45)]], {}), 47: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('clubs', 'Club'), ('rotarians', 'Rotariani'), ('countries', 'Paesi'), ('projects', 'Progetti')], 'label': 'dato'}), 48: ('wagtail.blocks.CharBlock', (), {'help_text': 'Mostrato se il dato non arriva.', 'label': 'valore di ripiego', 'required': False}), 49: ('wagtail.blocks.StructBlock', [[('source', 47), ('label', 42), ('fallback', 48)]], {}), 50: ('wagtail.blocks.ListBlock', (49,), {'label': 'numeri'}), 51: ('wagtail.blocks.StructBlock', [[('surface', 3), ('items', 50)]], {}), 52: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3'), ('4', '4')], 'label': 'colonne'}), 53: ('wagtail.blocks.CharBlock', (), {'label': 'nome'}), 54: ('cms.blocks.common.ImmagineBlock', (), {'label': 'logo', 'required': False}), 55: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternativa al logo per chi non ne ha uno.', 'label': 'emoji', 'max_length': 8, 'required': False}), 56: ('wagtail.blocks.URLBlock', (), {'label': 'sito', 'required': False}), 57: ('wagtail.blocks.IntegerBlock', (), {'default': 100, 'help_text': 'Alcuni loghi hanno molto spazio bianco intorno e vanno ingranditi per pesare come gli altri.', 'label': 'dimensione del logo (%)', 'max_value': 160, 'min_value': 60}), 58: ('wagtail.blocks.StructBlock', [[('name', 53), ('description', 32), ('logo', 54), ('emoji', 55), ('link', 56), ('logo_scale', 57)]], {}), 59: ('wagtail.blocks.ListBlock', (58,), {'label': 'partner'}), 60: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 32), ('columns', 52), ('surface', 3), ('items', 59)]], {}), 61: ('wagtail.blocks.TextBlock', (), {'label': 'citazione'}), 62: ('wagtail.blocks.CharBlock', (), {'label': 'autore', 'required': False}), 63: ('wagtail.blocks.CharBlock', (), {'label': 'ruolo', 'required': False}), 64: ('wagtail.blocks.CharBlock', (), {'label': 'luogo e data', 'required': False}), 65: ('wagtail.blocks.StructBlock', [[('quote', 61), ('author', 62), ('role', 63), ('place_and_date', 64)]], {}), 66: ('wagtail.blocks.TextBlock', (), {'label': 'testo'}), 67: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 66), ('surface', 3)]], {}), 68: ('wagtail.blocks.CharBlock', (), {'label': 'voce'}), 69: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'approfondimento', 'required': False}), 70: ('wagtail.blocks.StructBlock', [[('title', 68), ('link', 69)]], {}), 71: ('wagtail.blocks.ListBlock', (70,), {'label': 'voci'}), 72: ('wagtail.blocks.TextBlock', (), {'label': 'nota finale', 'required': False}), 73: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 9), ('items', 71), ('note', 72), ('surface', 3)]], {}), 74: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', '1'), ('2', '2'), ('3', '3')], 'label': 'colonne'}), 75: ('wagtail.blocks.EmailBlock', (), {'label': 'email', 'required': False}), 76: ('cms.blocks.common.ImmagineBlock', (), {'label': 'foto', 'required': False}), 77: ('wagtail.blocks.CharBlock', (), {'label': 'area'}), 78: ('wagtail.blocks.ListBlock', (77,), {'help_text': 'Es. i paesi seguiti da un referente.', 'label': 'aree di competenza', 'required': False}), 79: ('wagtail.blocks.StructBlock', [[('name', 53), ('role', 63), ('email', 75), ('photo', 76), ('areas', 78)]], {}), 80: ('wagtail.blocks.ListBlock', (79,), {'label': 'persone'}), 81: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 32), ('columns', 74), ('surface', 3), ('items', 80)]], {}), 82: ('wagtail.blocks.CharBlock', (), {'help_text': 'Sopra al riquadro. Es. Sviluppo tecnico', 'label': 'titolo', 'required': False}), 83: ('wagtail.blocks.CharBlock', (), {'label': 'sottotitolo', 'required': False}), 84: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es. Tech Solutions by', 'label': 'azienda', 'required': False}), 85: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'sito', 'required': False}), 86: ('wagtail.blocks.StructBlock', [[('heading', 82), ('subheading', 83), ('icon', 26), ('label', 84), ('name', 53), ('link', 85), ('surface', 3)]], {}), 87: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bronze', 'Bronzo'), ('silver', 'Argento'), ('gold', 'Oro')], 'label': 'livello'}), 88: ('wagtail.blocks.StructBlock', [[('tier', 87), ('title', 0), ('description', 1)]], {}), 89: ('wagtail.blocks.ListBlock', (88,), {'label': 'livelli'}), 90: ('wagtail.blocks.StructBlock', [[('title', 24), ('subtitle', 9), ('surface', 3), ('items', 89)]], {}), 91: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('route', 14), ('external_url', 15), ('visibility', 16)]], {'label': 'pulsante principale'}), 92: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 32), ('surface', 3), ('primary_cta', 91), ('secondary_cta', 18)]], {}), 93: ('cms.blocks.common.TipoArticoloBlock', (), {'label': 'tipo di articolo'}), 94: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid', 'Griglia'), ('calendar', 'Calendario'), ('list', 'Elenco')], 'label': 'visualizzazione'}), 95: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Vuoto per mostrarli tutti.', 'label': 'quanti al massimo', 'max_value': 100, 'min_value': 1, 'required': False}), 96: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'campo di ricerca', 'required': False}), 97: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'filtro per tag', 'required': False}), 98: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'filtro geografico', 'required': False}), 99: ('wagtail.blocks.StructBlock', [[('heading', 24), ('article_type', 93), ('accent', 33), ('layout', 94), ('columns', 25), ('limit', 95), ('show_search', 96), ('show_tag_filter', 97), ('show_geo_filter', 98)]], {}), 100: ('wagtail.blocks.CharBlock', (), {'label': 'etichetta del tab'}), 101: ('wagtail.blocks.StructBlock', [[('label', 100), ('article_type', 93), ('layout', 94), ('columns', 25)]], {}), 102: ('wagtail.blocks.ListBlock', (101,), {'label': 'tab'}), 103: ('wagtail.blocks.StructBlock', [[('heading', 24), ('accent', 33), ('tabs', 102), ('show_search', 96), ('show_tag_filter', 97), ('show_geo_filter', 98)]], {}), 104: ('cms.blocks.common.ImmagineBlock', (), {'label': 'immagine'})}, verbose_name='contenuto')),
            ],
            options={
                'verbose_name': 'pagina',
                'verbose_name_plural': 'pagine',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('key', models.SlugField(help_text='Identificatore tecnico, usato nelle API e negli URL. Non cambiarlo dopo che esistono articoli di questo tipo.', max_length=64, verbose_name='chiave')),
                ('name', models.CharField(help_text='Es. "Progetto", "Itinerario"', max_length=120, verbose_name='nome singolare')),
                ('name_plural', models.CharField(help_text='Es. "Progetti", "Itinerari"', max_length=120, verbose_name='nome plurale')),
                ('description', models.TextField(blank=True, help_text='A cosa serve questo tipo. Lo legge chi compone una pagina.', verbose_name='descrizione')),
                ('active_fields', models.JSONField(blank=True, default=list, verbose_name='campi attivi')),
                ('required_fields', models.JSONField(blank=True, default=list, verbose_name='campi obbligatori')),
                ('buttons', models.JSONField(blank=True, default=list, verbose_name='azioni sulla card')),
                ('can_publish', models.JSONField(blank=True, default=list, verbose_name='chi puo pubblicare')),
                ('body_blocks', models.JSONField(blank=True, default=list, verbose_name='blocchi ammessi nel corpo')),
                ('default_columns', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=3, help_text='Quante colonne usa la griglia, se la pagina non dice altro.', verbose_name='colonne')),
                ('new_article_label', models.CharField(blank=True, help_text='Es. "Proponi progetto". Se vuoto si usa "Nuovo " + nome.', max_length=80, verbose_name='etichetta del bottone di creazione')),
                ('uses_geo', models.BooleanField(default=False, help_text='Abilita regione e provincia su questo tipo di articolo.', verbose_name='usa la geografia')),
                ('external_url', models.URLField(blank=True, verbose_name='sito esterno')),
                ('external_email', models.EmailField(blank=True, max_length=254, verbose_name='email esterna')),
                ('external_phone', models.CharField(blank=True, max_length=32, verbose_name='telefono esterno')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'tipo di articolo',
                'verbose_name_plural': 'tipi di articolo',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(models.Model, modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='ArticleTypeInfoElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.SlugField(max_length=40, verbose_name='chiave')),
                ('icon', models.CharField(choices=[('Award', 'Award'), ('Bookmark', 'Bookmark'), ('Calendar', 'Calendar'), ('Clock', 'Clock'), ('Compass', 'Compass'), ('DollarSign', 'DollarSign'), ('Flag', 'Flag'), ('Globe', 'Globe'), ('Heart', 'Heart'), ('Mail', 'Mail'), ('MapPin', 'MapPin'), ('Phone', 'Phone'), ('Star', 'Star'), ('Tag', 'Tag'), ('Target', 'Target'), ('TrendingUp', 'TrendingUp'), ('Users', 'Users'), ('Utensils', 'Utensils'), ('Camera', 'Camera'), ('BookOpen', 'BookOpen'), ('Handshake', 'Handshake'), ('Lightbulb', 'Lightbulb'), ('Leaf', 'Leaf'), ('Music', 'Music'), ('Info', 'Info'), ('Code', 'Code')], max_length=40, verbose_name='icona')),
                ('label', models.CharField(max_length=80, verbose_name='etichetta')),
                ('article_type', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_elements', to='cms.articletype')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'elemento informativo',
                'verbose_name_plural': 'elementi informativi',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.SlugField(max_length=60, verbose_name='chiave')),
                ('label', models.CharField(max_length=80, verbose_name='etichetta')),
                ('article_type', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_tags', to='cms.articletype')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tag',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CMSDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='documents', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('collection', models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documenti',
                'abstract': False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
