# Generated by Django 5.2.7 on 2026-09-21 06:28

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import wagtail.models.media
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsdocument',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user'),
        ),
        migrations.AddField(
            model_name='cmsimage',
            name='collection',
            field=models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection'),
        ),
        migrations.AddField(
            model_name='cmsimage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='cmsimage',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user'),
        ),
        migrations.AddField(
            model_name='cmsrendition',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='cms.cmsimage'),
        ),
        migrations.AddField(
            model_name='geoarea',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.geoarea', verbose_name='contenuto in'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Una pagina creata nel CMS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='pagina del sito'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='submenu',
            field=models.ForeignKey(blank=True, help_text='Invece di una destinazione, apre un altro menu. E cosi che "Esplora" viene definito una volta e usato in piu punti.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usato_da', to='cms.menu', verbose_name='sottomenu'),
        ),
        migrations.AlterUniqueTogether(
            name='cmsrendition',
            unique_together={('image', 'filter_spec', 'focal_point_key')},
        ),
        migrations.AddConstraint(
            model_name='geoarea',
            constraint=models.UniqueConstraint(fields=('parent', 'key'), name='uniq_geoarea_parent_key'),
        ),
    ]
