# Generated by Django 5.2.7 on 2026-09-01 11:33

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('key', models.SlugField(help_text='Identificatore tecnico, usato nelle API e negli URL. Non cambiarlo dopo che esistono articoli di questo tipo.', max_length=64, verbose_name='chiave')),
                ('name', models.CharField(help_text='Es. "Progetto", "Itinerario"', max_length=120, verbose_name='nome singolare')),
                ('name_plural', models.CharField(help_text='Es. "Progetti", "Itinerari"', max_length=120, verbose_name='nome plurale')),
                ('description', models.TextField(blank=True, help_text='A cosa serve questo tipo. Lo legge chi compone una pagina.', verbose_name='descrizione')),
                ('active_fields', models.JSONField(blank=True, default=list, verbose_name='campi attivi')),
                ('required_fields', models.JSONField(blank=True, default=list, verbose_name='campi obbligatori')),
                ('buttons', models.JSONField(blank=True, default=list, verbose_name='azioni sulla card')),
                ('can_publish', models.JSONField(blank=True, default=list, verbose_name='chi puo pubblicare')),
                ('body_blocks', models.JSONField(blank=True, default=list, verbose_name='blocchi ammessi nel corpo')),
                ('default_columns', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=3, help_text='Quante colonne usa la griglia, se la pagina non dice altro.', verbose_name='colonne')),
                ('new_article_label', models.CharField(blank=True, help_text='Es. "Proponi progetto". Se vuoto si usa "Nuovo " + nome.', max_length=80, verbose_name='etichetta del bottone di creazione')),
                ('uses_geo', models.BooleanField(default=False, help_text='Abilita regione e provincia su questo tipo di articolo.', verbose_name='usa la geografia')),
                ('external_url', models.URLField(blank=True, verbose_name='sito esterno')),
                ('external_email', models.EmailField(blank=True, max_length=254, verbose_name='email esterna')),
                ('external_phone', models.CharField(blank=True, max_length=32, verbose_name='telefono esterno')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'tipo di articolo',
                'verbose_name_plural': 'tipi di articolo',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(models.Model, modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='ArticleTypeInfoElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.SlugField(max_length=40, verbose_name='chiave')),
                ('icon', models.CharField(choices=[('Award', 'Award'), ('Bookmark', 'Bookmark'), ('Calendar', 'Calendar'), ('Clock', 'Clock'), ('Compass', 'Compass'), ('DollarSign', 'DollarSign'), ('Flag', 'Flag'), ('Globe', 'Globe'), ('Heart', 'Heart'), ('Mail', 'Mail'), ('MapPin', 'MapPin'), ('Phone', 'Phone'), ('Star', 'Star'), ('Tag', 'Tag'), ('Target', 'Target'), ('TrendingUp', 'TrendingUp'), ('Users', 'Users'), ('Utensils', 'Utensils'), ('Camera', 'Camera'), ('BookOpen', 'BookOpen'), ('Handshake', 'Handshake'), ('Lightbulb', 'Lightbulb'), ('Leaf', 'Leaf'), ('Music', 'Music'), ('Info', 'Info')], max_length=40, verbose_name='icona')),
                ('label', models.CharField(max_length=80, verbose_name='etichetta')),
                ('article_type', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_elements', to='cms.articletype')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'elemento informativo',
                'verbose_name_plural': 'elementi informativi',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.SlugField(max_length=60, verbose_name='chiave')),
                ('label', models.CharField(max_length=80, verbose_name='etichetta')),
                ('article_type', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_tags', to='cms.articletype')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tag',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='articletype',
            constraint=models.UniqueConstraint(fields=('key', 'locale'), name='uniq_articletype_key_locale'),
        ),
        migrations.AlterUniqueTogether(
            name='articletype',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='articletypeinfoelement',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='articletypetag',
            unique_together={('translation_key', 'locale')},
        ),
    ]
