# Generated by Django 5.2.7 on 2026-09-01 13:48

import django.db.models.deletion
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_articletype_articletypeinfoelement_articletypetag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('country', 'Nazione'), ('region', 'Regione'), ('province', 'Provincia'), ('city', 'Comune')], max_length=12, verbose_name='livello')),
                ('key', models.SlugField(max_length=80, verbose_name='chiave')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Nomi in altre lingue, es. {"en": "Apulia"}. Se manca si usa il nome italiano.', verbose_name='traduzioni')),
                ('code', models.CharField(blank=True, help_text='Sigla della provincia (BA, MI) o codice della nazione (IT).', max_length=8, verbose_name='sigla')),
                ('path', models.CharField(db_index=True, editable=False, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='attiva')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.geoarea', verbose_name='contenuto in')),
            ],
            options={
                'verbose_name': 'area geografica',
                'verbose_name_plural': 'aree geografiche',
                'ordering': ['path'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'key'), name='uniq_geoarea_parent_key')],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
