# Generated by Django 5.2.7 on 2026-09-27 15:20

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletypetag',
            name='category',
            field=models.SlugField(blank=True, help_text='La chiave di una delle categorie definite qui sopra. Lasciala vuota se il tag non appartiene a nessun gruppo.', max_length=60, verbose_name='categoria'),
        ),
        migrations.CreateModel(
            name='ArticleTypeTagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.SlugField(help_text='Identificatore tecnico, es. "stato". E quello che si scrive accanto a ogni tag.', max_length=60, verbose_name='chiave')),
                ('label', models.CharField(help_text='Il titolo del gruppo nella tendina. Es. "Stato".', max_length=80, verbose_name='etichetta')),
                ('article_type', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_categories', to='cms.articletype')),
            ],
            options={
                'verbose_name': 'categoria di tag',
                'verbose_name_plural': 'categorie di tag',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
