# Generated by Django 5.2.7 on 2026-09-01 14:27

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_geoarea'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('key', models.SlugField(help_text='Identificatore usato dal frontend. Non cambiarlo se il menu e gia in uso.', max_length=64, verbose_name='chiave')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, help_text='A cosa serve questo menu e dove compare.', verbose_name='descrizione')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menu',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=120, verbose_name='etichetta')),
                ('route', models.CharField(blank=True, help_text="Una rotta dell'applicazione, es. /rota-space. Serve per le pagine che restano codice.", max_length=200, verbose_name='percorso interno')),
                ('external_url', models.URLField(blank=True, verbose_name='indirizzo esterno')),
                ('icon', models.CharField(blank=True, choices=[('Award', 'Award'), ('Bookmark', 'Bookmark'), ('Calendar', 'Calendar'), ('Clock', 'Clock'), ('Compass', 'Compass'), ('DollarSign', 'DollarSign'), ('Flag', 'Flag'), ('Globe', 'Globe'), ('Heart', 'Heart'), ('Mail', 'Mail'), ('MapPin', 'MapPin'), ('Phone', 'Phone'), ('Star', 'Star'), ('Tag', 'Tag'), ('Target', 'Target'), ('TrendingUp', 'TrendingUp'), ('Users', 'Users'), ('Utensils', 'Utensils'), ('Camera', 'Camera'), ('BookOpen', 'BookOpen'), ('Handshake', 'Handshake'), ('Lightbulb', 'Lightbulb'), ('Leaf', 'Leaf'), ('Music', 'Music'), ('Info', 'Info')], max_length=40, verbose_name='icona')),
                ('visibility', models.CharField(choices=[('always', 'Sempre'), ('authenticated', 'Solo a chi ha fatto accesso'), ('anonymous', 'Solo a chi non ha fatto accesso')], default='always', max_length=16, verbose_name='visibile')),
                ('roles', models.JSONField(blank=True, default=list, help_text='Lascia vuoto per mostrarla a tutti.', verbose_name='solo per questi ruoli')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='apri in una nuova scheda')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menu')),
                ('page', models.ForeignKey(blank=True, help_text='Una pagina creata nel CMS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='pagina del sito')),
                ('submenu', models.ForeignKey(blank=True, help_text='Invece di una destinazione, apre un altro menu. E cosi che "Esplora" viene definito una volta e usato in piu punti.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usato_da', to='cms.menu', verbose_name='sottomenu')),
            ],
            options={
                'verbose_name': 'voce di menu',
                'verbose_name_plural': 'voci di menu',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('key', 'locale'), name='uniq_menu_key_locale'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('translation_key', 'locale')},
        ),
    ]
