# Generated by Django 5.2.7 on 2026-10-01 11:23

import traduzione.lingue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_blocchi_elenco_vuoto_icone_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='source_locale',
            field=models.CharField(choices=traduzione.lingue.scelte, db_index=True, default='it', help_text="La lingua in cui stai scrivendo. Il sito la traduce in tutte le altre, e a chi legge dice in quale e' stata scritta.", max_length=10, verbose_name='lingua di stesura'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='source_locale',
            field=models.CharField(choices=traduzione.lingue.scelte, db_index=True, default='it', help_text="La lingua in cui stai scrivendo. Il sito la traduce in tutte le altre, e a chi legge dice in quale e' stata scritta.", max_length=10, verbose_name='lingua di stesura'),
        ),
    ]
