# Generated by Django 5.2.7 on 2026-09-18 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('source_locale', models.CharField(db_index=True, default='it', max_length=10, verbose_name='lingua di stesura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_language', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('provider', models.CharField(choices=[('claude', 'Modello linguistico'), ('identita', 'Nessuna traduzione (testo originale)'), ('umano', 'Scritta da una persona')], max_length=20)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('human_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_locale', models.CharField(db_index=True, default='it', max_length=10, verbose_name='lingua di stesura')),
                ('content_html', models.TextField(blank=True)),
                ('comments_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_language', models.CharField(max_length=10)),
                ('translated_title', models.TextField()),
                ('translated_description', models.TextField()),
                ('provider', models.CharField(choices=[('claude', 'Modello linguistico'), ('identita', 'Nessuna traduzione (testo originale)'), ('umano', 'Scritta da una persona')], max_length=20)),
                ('detected_source_language', models.CharField(blank=True, max_length=10, null=True)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('human_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
