# Generated by Django 5.2.7 on 2026-09-18 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='commenttranslation',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.post'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='forum.post'),
        ),
        migrations.AddIndex(
            model_name='commenttranslation',
            index=models.Index(fields=['comment', 'target_language'], name='forum_comme_comment_521b6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commenttranslation',
            unique_together={('comment', 'target_language')},
        ),
        migrations.AddIndex(
            model_name='posttranslation',
            index=models.Index(fields=['post', 'target_language'], name='forum_postt_post_id_75e31a_idx'),
        ),
        migrations.AddIndex(
            model_name='posttranslation',
            index=models.Index(fields=['target_language'], name='forum_postt_target__bc5162_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posttranslation',
            unique_together={('post', 'target_language')},
        ),
    ]
