# Generated by Django 5.2.7 on 2025-12-04 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_language', models.CharField(max_length=10)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_description', models.TextField()),
                ('provider', models.CharField(choices=[('deepl', 'DeepL'), ('google', 'Google Cloud Translation')], max_length=20)),
                ('detected_source_language', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='forum.post')),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'target_language'], name='forum_postt_post_id_75e31a_idx'), models.Index(fields=['target_language'], name='forum_postt_target__bc5162_idx')],
                'unique_together': {('post', 'target_language')},
            },
        ),
    ]
