# Generated by Django 5.2.8 on 2026-09-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_comments_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='translated_title',
            field=models.TextField(),
        ),
    ]
