# Generated by Django 5.2.7 on 2025-12-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_content_html'),
        ('forum', '0003_posttranslation'),
    ]

    operations = [
    ]
