# Generated by Django 5.2.7 on 2026-09-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_posttranslation_translated_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='source_locale',
            field=models.CharField(db_index=True, default='it', max_length=10, verbose_name='lingua di stesura'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_locale',
            field=models.CharField(db_index=True, default='it', max_length=10, verbose_name='lingua di stesura'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='human_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='provider',
            field=models.CharField(choices=[('claude', 'Modello linguistico'), ('identita', 'Nessuna traduzione (testo originale)'), ('umano', 'Scritta da una persona')], max_length=20),
        ),
        migrations.CreateModel(
            name='CommentTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_language', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('provider', models.CharField(choices=[('claude', 'Modello linguistico'), ('identita', 'Nessuna traduzione (testo originale)'), ('umano', 'Scritta da una persona')], max_length=20)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('human_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='forum.comment')),
            ],
            options={
                'indexes': [models.Index(fields=['comment', 'target_language'], name='forum_comme_comment_521b6b_idx')],
                'unique_together': {('comment', 'target_language')},
            },
        ),
    ]
