# Generated by Django 5.2.7 on 2026-09-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatparticipant_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_locale',
            field=models.CharField(default='it', max_length=10, verbose_name='lingua di stesura'),
        ),
        migrations.AddField(
            model_name='messagetranslation',
            name='human_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagetranslation',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='messagetranslation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messagetranslation',
            name='provider',
            field=models.CharField(choices=[('claude', 'Modello linguistico'), ('identita', 'Nessuna traduzione (testo originale)'), ('umano', 'Scritta da una persona')], max_length=20),
        ),
    ]
