# Generated by Django 5.2.7 on 2025-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatparticipant_remove_chat_unique_direct_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('direct', 'Chat Diretta'), ('group', 'Chat di Gruppo'), ('forum', 'Forum Globale')], default='direct', max_length=10),
        ),
    ]
