# Generated by Django 5.2.7 on 2025-11-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('direct', 'Chat Diretta'), ('group', 'Chat di Gruppo')], default='direct', max_length=10),
        ),
    ]
