# Generated by Django 5.2.7 on 2025-11-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_messagetranslation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagetranslation',
            new_name='chat_messag_message_b6e6c9_idx',
            old_name='chat_message_message_1a73a1_idx',
        ),
        migrations.RenameIndex(
            model_name='messagetranslation',
            new_name='chat_messag_target__883b77_idx',
            old_name='chat_message_target__62e6f5_idx',
        ),
    ]
