# Generated by Django 5.2.7 on 2025-12-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_chat_message_message_1a73a1_idx_chat_messag_message_b6e6c9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('direct', 'Chat Diretta'), ('group', 'Chat di Gruppo'), ('general_group', 'Chat di Gruppo Generale')], default='direct', max_length=15),
        ),
    ]
