# Generated by Django 5.2.7 on 2025-12-23 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_chat_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='related_clubs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'CLUB'}, related_name='gemellaggi_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('direct', 'Chat Diretta'), ('group', 'Chat di Gruppo'), ('general_group', 'Chat di Gruppo Generale'), ('gemellaggio', 'Gemellaggio')], default='direct', max_length=15),
        ),
    ]
